name: Register Schema to Confluent Cloud

# This workflow is triggered on a push event to any branch.
# It specifically watches for changes to files with a .avsc extension
# inside the 'schemas' directory.
on:
  push:
    paths:
      - 'schemas/*.avsc'

jobs:
  register-schema:
    runs-on: ubuntu-latest
    
    environment: development
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'schemas/*.avsc'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Register schema with Confluent Cloud
        env:
          CCLOUD_SR_API_KEY: ${{ secrets.CCLOUD_SR_API_KEY }}
          CCLOUD_SR_API_SECRET: ${{ secrets.CCLOUD_SR_API_SECRET }}
          SCHEMA_REGISTRY_URL: "https://psrc-1dx3ljw.ap-southeast-1.aws.confluent.cloud"
        run: |
          echo "The following files were updated:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Iterate over each file for a specific task
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Registering schema with name: $file"

            jq --null-input --raw-output --argfile schema user.avsc '{schema: $schema | tostring}' | \
            curl -X POST \
            -H "Content-Type: application/vnd.schemaregistry.v1+json" \
            --user 27EAYRMQAQMJFLGK:cfltz6zJx9Kmz8v3d0MTkwzbvjas8F+fNBfPTgjkT6hVjwQrvYtoUGlBTpYkgwFA \
            --data @- \
            https://psrc-1dx3ljw.ap-southeast-1.aws.confluent.cloud/subjects/users-value/versions
          done
